### ISSUE TITLE
MainService Crash  

### ISSUE THREAD

**Issue by ELY3M** [vmiklos/plees-tracker#285]
I think you need to change the flag in MainService like I did in my build of the app.      

2022-05-23 12:58:10.467 22384-22384/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: hu.vmiklos.plees_tracker, PID: 22384
    java.lang.RuntimeException: Unable to start service hu.vmiklos.plees_tracker.MainService@9575c59 with Intent { cmp=hu.vmiklos.plees_tracker/.MainService }: java.lang.IllegalArgumentException: hu.vmiklos.plees_tracker: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
        at android.app.ActivityThread.access$2200(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalArgumentException: hu.vmiklos.plees_tracker: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
        at android.app.PendingIntent.getActivity(PendingIntent.java:451)
        at android.app.PendingIntent.getActivity(PendingIntent.java:415)
        at hu.vmiklos.plees_tracker.MainService.onStartCommand(MainService.kt:40)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
        	... 9 more

**Comment by vmiklos** [comment]
How do I reproduce this?

**Comment by vmiklos** [comment]
Ah, you must be on Android 12, where this indeed happens. Now that I updated my emulator to Android 12, I also see this at runtime.

Note to self: the stupid defaults now make it impossible to turn of the emulator, https://stackoverflow.com/questions/71260174/android-emulator-power-off-button-does-not-work-when-using-avd-with-system-image is an effective workaround.
